# Experiment
device_id: cpu 
seed: 42
epochs: 100
max_episode_steps: 200
gamma: 0.95

# Meta-parameters
inner_steps: 2

# TODO: Parse network sizes
actor_critic:
  hidden_size: 128
  # actor_hidden_sizes: [64, 64, 64]
  # critic_hidden_sizes: [64, 64, 64]

a2c:
  lr: 3.0e-2
  max_grad_norm: 0.5
  value_coeff: 0.5
